// scriptc has no bundler-side text imports (`with { type: 'text' }` is a Bun
// feature), so the agent-context payload is baked into a TypeScript module
// that both toolchains can compile. Run via `bun run gen`.
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const src = join(import.meta.dir, '..', 'src', 'agent-context.txt')
const out = join(import.meta.dir, '..', 'src', 'agent-context.gen.ts')

const text = readFileSync(src, 'utf8')

writeFileSync(
  out,
  `// GENERATED by scripts/gen-agent-context.ts — edit src/agent-context.txt instead.\n` +
    `export const agentContext =\n` +
    `  ${JSON.stringify(text)}\n`
)

process.stderr.write(`wrote ${out} (${text.length} chars)\n`)
