// Generate src/content.gen.ts with base64-encoded text assets.
//
// Why base64: the raw texts (install.sh, agent context, code samples) look
// like shell/python payloads to Cloudflare's API WAF, which rejects the
// script upload with an HTML 403. Encoding at build time keeps the deploy
// body inert; the Worker decodes at runtime. Single source of truth stays
// in the repo files.
const read = (p: string) => Bun.file(new URL(p, import.meta.url)).text()

const [installSh, llmsTxt, skillMd] = await Promise.all([
  read('../scripts/install.sh'),
  read('../src/agent-context.txt'),
  read('../skills/ax/SKILL.md'),
])

const duelBefore = `python3 - <<'PY'
import re
h=open('page.html',errors='replace').read()
blocks=re.findall(
  r'<li class="lesson">([\\s\\S]*?)</li>',h)
rows=[]
for b in blocks:
  href=re.search(r'href="([^"]+)"',b)
  title=re.search(r'<a [^>]*>([^<]+)</a>',b)
  ...
PY`

const b64 = (s: string) => Buffer.from(s, 'utf-8').toString('base64')

// Images are generated by og.ts (run it first when the design changes).
const img = async (p: string) =>
  Buffer.from(await Bun.file(new URL(p, import.meta.url)).arrayBuffer()).toString('base64')
const ogPng = await img('src/og.png')
const faviconPng = await img('src/favicon.png')
const touchIconPng = await img('src/apple-touch-icon.png')

const out = `// AUTO-GENERATED by gen.ts — do not edit. Regenerate with: bun gen.ts
const d = (s: string) => new TextDecoder().decode(Uint8Array.from(atob(s), (c) => c.charCodeAt(0)))
export const installSh = d('${b64(installSh)}')
export const llmsTxt = d('${b64(llmsTxt)}')
export const skillMd = d('${b64(skillMd)}')
export const duelBefore = d('${b64(duelBefore)}')
export const ogPngB64 = '${ogPng}'
export const faviconPngB64 = '${faviconPng}'
export const touchIconPngB64 = '${touchIconPng}'
`

await Bun.write(new URL('src/content.gen.ts', import.meta.url), out)
console.log('wrote src/content.gen.ts')
